### ISSUE TITLE
The addon should default the app to the ember-gdrive adapter

### ISSUE THREAD

**Issue by begedin** [coderly/ember-gdrive#82]
NOTE: We decided to go ahead with what's described bellow, so I edited the task.

@venkatd 

I was thinking we could add `app/adapters/application.js` to the add-on which exports the default `addon/adapters/adapter.js`. That way, the default application adapter would immediately be the gdrive adapter and we would eliminate a step from the installation process.

Would that make sense?

An additional argument for this is that we're already doing kind of the the same with setting the default authenticator, except it's done through an initializer.

**Comment by begedin** [comment]
To elaborate on this a bit.

What we'd do here is
* move `app/adapters/adapter.js` to `addon/adapters/adapter.js`
* rename it to something that makes more sense, maybe `google-drive-document`
* add `app/adapters/application.js` which imports and then exports the above adapter

The positive result of that is we get to remove `app/adapters/application.js` from Storypad and ember-gdriveTodoMVC and eliminate that step from the add-on installation process.

The possibly negative result is that any app using ember-gdrive is defaulted to this adapter automatically. I'm not sure this is an actual negative, though. We already require routing to be structured in a certain way that would probably make it quite difficult to use alternative application-wide adapters alongside this one.

**Comment by venkatd** [comment]
I like this idea. Let's go ahead and do it.

**Comment by begedin** [comment]
@venkatd: Extra question.

Since storypad switches between the gdrive adapter and the custom fixture adapter, and since that adapter seems to be pretty closely tied to ember-gdrive anyway, should we move it

https://github.com/venkatd/storypad/blob/development/app/lib/custom-fixture-adapter.js

as well as the adapter switching logic in 

https://github.com/venkatd/storypad/blob/development/app/adapters/application.js

to ember-gdrive? I'd have to figure out if we need to do anything with the whole window.testDocument thing, but I think it would make sense.

**Comment by venkatd** [comment]
The custom fixture adapter is a workaround for a bug in the fixture adapter where relationships will sometimes get deleted. This would occur because a serializer wouldn't serialize async relationships that weren't loaded which would cause the relationships to get wiped out on save. This is why I call `_loadRelationships` in every method.

However, this may no longer be an issue with the (latest version of ember-data)[http://emberjs.com/blog/2014/12/25/ember-data-1-0-beta-14-released.html] which now handles partial payloads (unverified).

I feel like the custom fixture adapter isn't something that belongs in ember-gdrive. What do you see as the connection between the custom fixture adapter and ember-gdrive?

**Comment by begedin** [comment]
If we're abandoning the the `testDocument`, then there's no connection anymore, so you can ignore this. When the `testDocument` was still present, the application adapter was exporting a `CustomFixtureAdapter` in case of `window.testDocument` being true.
